name: Metamask CI

on: push

jobs:
  build:
    env:
      MM_SEED_PHRASE: ${{ secrets.MM_SEED_PHRASE }}
      MM_PASSWORD: ${{ secrets.MM_PASSWORD }}
      AURORA_MAINNET_NETWORK_NAME: ${{ vars.AURORA_MAINNET_NETWORK_NAME }}
      AURORA_MAINNET_NETWORK_URL: ${{ vars.AURORA_MAINNET_NETWORK_URL }}
      AURORA_MAINNET_CHAIN_ID: ${{ vars.AURORA_MAINNET_CHAIN_ID }}
      NEAR_NETWORK_ENVIRONMENT: ${{ vars.NEAR_NETWORK_ENVIRONMENT }}
      NEAR_MAINNET_NETWORK_NAME: ${{ vars.NEAR_MAINNET_NETWORK_NAME }}
      NEAR_MAINNET_NETWORK_URL: ${{ vars.NEAR_MAINNET_NETWORK_URL }}
      NEAR_MAINNET_CHAIN_ID: ${{ vars.NEAR_MAINNET_CHAIN_ID }}
      NEAR_MAINNET_BLOCK_EXPLORER_URL: ${{ vars.NEAR_MAINNET_BLOCK_EXPLORER_URL }}
      NEAR_TESTNET_NETWORK_NAME: ${{ vars.NEAR_TESTNET_NETWORK_NAME }}
      NEAR_TESTNET_NETWORK_URL: ${{ vars.NEAR_TESTNET_NETWORK_URL }}
      NEAR_TESTNET_CHAIN_ID: ${{ vars.NEAR_TESTNET_CHAIN_ID }}
      PW_TEST_HTML_REPORT_OPEN: ${{ vars.PW_TEST_HTML_REPORT_OPEN }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Yarn
        run: npm install -g yarn

      - name: Print variable
        run: echo ${{ vars.AURORA_MAINNET_CHAIN_ID }}

      - name: Install linux deps
        run: |
          sudo apt-get install --no-install-recommends -y \
          fluxbox \
          xvfb

      - name: Run xvfb and fluxbox
        run: |
          Xvfb :0 -screen 0 1920x1080x24 -listen tcp -ac &
          fluxbox -display :0.0 &
        env:
          DISPLAY: :0.0

      - run: yarn install --immutable
      - run: yarn playwright install --with-deps
      - run: xvfb-run yarn synpress
      - run: xvfb-run yarn playwright-aurora test
