name: E2E UI automation tests daily trigger

on:
    workflow_dispatch:
    schedule:
      - cron: '0 8,14 * * 1-5'

jobs:
  e2e-daily:
    strategy:
      matrix:
        tag: ['@aurora-plus', '@web3-wallet']
    uses: ./.github/workflows/e2e-worker.yml
      with:
        tag: ${{ matrix.tag }}
