name: Run E2E tests

on:
  pull_request:
  push:
    branches:
      - e2e

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - name: Install
        run: yarn install --frozen-lockfile --non-interactive --prefer-offline
      - name: Check types
        run: yarn run test:headless
