name: Metamask CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 120
          install-chromedriver: true

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install linux deps
        run: |
          sudo apt-get install --no-install-recommends -y \
          fluxbox \
          xvfb

      - name: Run xvfb and fluxbox
        run: |
          Xvfb :0 -screen 0 1920x1080x24 -listen tcp -ac &
          fluxbox -display :0.0 &
        env:
          DISPLAY: :0.0

      - run: yarn install --immutable
      - run: yarn playwright install --with-deps
      - run: xvfb-run yarn test-web-wallet
